spring:
  datasource:
    url: jdbc:mysql://192.168.118.194:3306/security
    username: root
    password: F235vk26
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

security:
  jwt:
    uri: /auth/**
    header: 'Authorization'
    prefix: 'Bearer '
    expiration: #{24*60*60}
    secret: 'JwtSecretKey'