spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aseksenali/software_engineering
          search-paths:
            - "config-properties"
            - "config-properties/{application}/{profile}"
          username: aseksenali
          password: Aset3953441